name: Build Angular & Push to Docker Hub

on:
  push:
    branches: [ "main", "master" ] # Se activa cuando subes cambios a main o master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar tu código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Loguearse en Docker Hub (Usa los secretos que creaste)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Configurar motor de Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Compilar y Subir (Build & Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/velzon-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/velzon-frontend:${{ github.sha }}
          # --- ZONA DE OPTIMIZACIÓN ---
          # Esto le dice a GitHub: "Usa el caché interno para no instalar todo de nuevo"
          cache-from: type=gha
          cache-to: type=gha,mode=max